"""Drop defaultStoreID

Revision ID: 4fc13cff3a8e
Revises: 9b373074bb20
Create Date: 2025-10-20 22:00:08.768452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc13cff3a8e'
down_revision: Union[str, Sequence[str], None] = '9b373074bb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_metadata_default_store_id_fkey'), 'users_metadata', type_='foreignkey')
    op.drop_column('users_metadata', 'default_store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_metadata', sa.Column('default_store_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_metadata_default_store_id_fkey'), 'users_metadata', 'stores', ['default_store_id'], ['id'])
    # ### end Alembic commands ###
