"""Add empty user metadata

Revision ID: 6a8cac00a77e
Revises: 10ade2599b25
Create Date: 2025-08-31 14:30:08.855564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8cac00a77e'
down_revision: Union[str, Sequence[str], None] = '10ade2599b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_metadata', 'default_store_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_metadata', 'default_store_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
