"""Remove nullable name

Revision ID: b83a07791b8d
Revises: 6a8cac00a77e
Create Date: 2025-09-27 11:42:11.656357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83a07791b8d'
down_revision: Union[str, Sequence[str], None] = '6a8cac00a77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stores', sa.Column('status', sa.String(length=255), nullable=False))
    op.add_column('stores', sa.Column('job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stores', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'job_id')
    op.drop_column('stores', 'status')
    op.drop_table('jobs')
    # ### end Alembic commands ###
