"""Fix status enum

Revision ID: f7636c5bab59
Revises: 1c6d7ab6d115
Create Date: 2025-10-07 21:21:30.930872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7636c5bab59'
down_revision: Union[str, Sequence[str], None] = '1c6d7ab6d115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns_metadata',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.add_column('campaigns', sa.Column('url', sa.String(length=2048), nullable=False))
    op.add_column('campaigns', sa.Column('job_id', sa.UUID(), nullable=True))
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('active', 'draft', 'archived', name='campaign_status'),
               type_=sa.Enum('setup', 'active', 'archived', name='campaign_state', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'campaigns', 'jobs', ['job_id'], ['id'])
    op.alter_column('stores', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('setup', 'active', 'archived', name='store_state', native_enum=False, create_constraint=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'status',
               existing_type=sa.Enum('setup', 'active', 'archived', name='store_state', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.alter_column('campaigns', 'status',
               existing_type=sa.Enum('setup', 'active', 'archived', name='campaign_state', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('active', 'draft', 'archived', name='campaign_status'),
               existing_nullable=False)
    op.drop_column('campaigns', 'job_id')
    op.drop_column('campaigns', 'url')
    op.drop_table('campaigns_metadata')
    # ### end Alembic commands ###
